yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
]

yatube/users/urls.py
from django.contrib.auth import views

from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/', views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/', LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/', LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_change/', PasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'password_change/done/', PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    path(
        'password_reset/', PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/', PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/', PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    )

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:#BF442A" >Art</span ><span style="color: #2ABFA2">Community</span>   
</footer>

yatube/templates/includes/header.html
{% load static %} 
  {% with request.resolver_match.view_name as view_name %}
      <nav class="navbar navbar-light navbar-fixed-top" style="background-color: light">
        <div class="p-2 mb-2 container fixed-top" style="background-color: #232323">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
              <img src="{% static 'img/fox-logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              <span style="color:#BF442A" >Art</span ><span style="color: #2ABFA2">Community</span>
            </a>
          <ul class="nav nav-wrap">
            <li class="nav-item"> 
              <a class="nav-link" 
                href="{% url 'about:author'  %}" {% if view_name  == 'about:author' %}style="color: #16A085; text-decoration: none"{% else %}style="color: #E5E7E9 ; text-decoration: none"{% endif %}>Об авторе</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" 
                href="{% url 'about:tech' %}" {% if view_name  == 'about:tech' %}style="color: #16A085; text-decoration: none"{% else %}style="color: #E5E7E9 ; text-decoration: none"{% endif %}>Технологии</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link" 
                href="{% url 'posts:post_create' %}" {% if view_name  == 'posts:post_create' %}style="color: #16A085; text-decoration: none"{% else %}style="color: #E5E7E9 ; text-decoration: none"{% endif %}>Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light"
                href="{% url 'users:password_change' %}"  {% if view_name  == 'users:password_change' %}style="color: #16A085; text-decoration: none"{% else %}style="color: #E5E7E9 ; text-decoration: none"{% endif %}>Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a href="{% url 'users:logout' %}">
                <button type="button" class="btn btn-warning">
                  Выйти
                </button>
              </a>
            </li>

            {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:login' %}">
                <button type="button" class="btn btn-success">
                  Войти
                </button>
              </a>       
            </li>

            {% endif %}
          </ul>
        </div>
      </nav>
  {% endwith %} 