yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Выбери группу',
        max_length=200,
        help_text='Название группы'
    )
    slug = models.SlugField(unique=True)
    description = models.TextField(
        'Опиши группу',
        help_text='Описание группы'
    )

    class Meta:
        verbose_name = 'group'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Введи текст',
        help_text='Текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор поста'
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        help_text='Дата публикации'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Поле группы',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        help_text='Группа'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        'Введи текст',
        help_text='Добавь, пожалуйста, свой комментарий'
    )
    created = models.DateTimeField(
        'Дата создания комента',
        auto_now_add=True,
        help_text='Дата публикации комента'
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        help_text='Кто подписан')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        help_text='На кого подписан')

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'), name='unique_relations'),
        )

    def __str__(self):
        return f'{self.user.username} follows {self.author.username}'

yatube/posts/forms.py
from django import forms
from django.forms.widgets import Textarea
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': Textarea,
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)
        widgets = {
            'text: TextArea',
        }

yatube/posts/views.py
from .forms import PostForm, CommentForm
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, Follow
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from yatube.settings import POSTS_PER_PAGE


User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    user_posts = user.posts.all()
    paginator = Paginator(user_posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_count = user_posts.count()

    following = Follow.objects.filter(
        user=request.user.id,
        author=user,
    ).exists()

    context = {
        'author': user,
        'page_obj': page_obj,
        'posts_count': posts_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author_posts_count = post.author.posts.all().count()
    comments = post.comments.all()
    if post.author != request.user:
        if_author = False
    else:
        if_author = True
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'author_posts_count': author_posts_count,
        'comments': comments,
        'if_author': if_author,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method != 'POST':
        form = PostForm()
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    if request.method != "POST":
        form = PostForm(instance=post)
        return render(request, 'posts/create_post.html',
                      {'form': form, 'post_id': post_id, 'is_edit': True})
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'post_id': post_id, 'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if username != request.user.username:
        author_wanna_follow = User.objects.get(username=username)
        Follow.objects.get_or_create(user=request.user,
                                     author=author_wanna_follow)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author_stop_follow = User.objects.get(username=username)
    follow_object = Follow.objects.filter(user=request.user,
                                          author=author_stop_follow)
    if follow_object.exists():
        follow_object.delete()
    return redirect('posts:profile', username=username)


def post_delete(request, post_id):
    post_to_delete = Post.objects.filter(id=post_id)
    if post_to_delete.exists():
        post_to_delete.delete()
    return redirect('posts:index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
  Новый пост
  {% endblock %}
  {% block content %}
  {% load user_filters %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header"  style="background-color: #BF442A">       
              {% if is_edit %}
               Редактировать запись
              {% else %}
               Добавить запись
              {% endif %}             
            </div>
            <div class="card-body" style="background-color: #232323">

              {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger" >
                  {{ error|escape }}
                </div>
              {% endfor %}
              {% endif %}
              
              <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post_id=post_id%}{% else %}{% url 'posts:post_create' %}{% endif%}">
              
                {% csrf_token %}

                {% for field in form %} 

                  <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %} style="background-color: #232323">
                    <label for="{{ field.id_text }}" class="form-group row my-6 p-3" >{{ field.label }}
                      {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}</label>
                        <div class="col-md-12">
                          {{ field|addclass:"form-control" }}
                        </div>                
                  </div>

                {% endfor %}

                <div class="d-flex justify-content-end" style=margin-top:3% >
                  <button type="submit" class="btn btn-warning " style="color: #232323; text-decoration: none">
                    {% if is_edit %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                  </button>  
                </div>
              </form> 
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}
{% block title %}
  Посты авторов
{% endblock %}
{% block content %}

  <h1 style="margin-top: 100px; margin-bottom: 30px"> Записи мох авторов </h1>
  {% include 'posts/includes/switcher.html' %}

  {% for post in page_obj %}
  <ul>
    <li>
      <a href="{% url 'posts:profile' username=post.author.username %}" style="color: #BF442A; text-decoration: none">
        Автор: {{ post.author.get_full_name }}
      </a>  
    </li>
    <li style="color: #2ABFA2">
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <a href="{% url 'posts:post_detail' post_id=post.id %}" style="color: #E5E7E9; text-decoration: none">{{ post.text }}</a>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  {% if post.group %}    
    <p>    
      <a href="{% url 'posts:group_posts' slug=post.group.slug %}" style="color:#2AA6BF; text-decoration: none">{{  post.group.title  }} *</a>
    </p>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}
{% endcache %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Сообщество {{ group.title }}
{% endblock %}
{% block content %}
  <h1 style="margin-top: 48px; margin-bottom: 10px">{{ group.title }}</h1>
  <h4 style="margin-bottom: 30px">{{ group.description }}</h4>
  {% for post in page_obj %}
    <ul>
      <li>
        <a href="{% url 'posts:profile' username=post.author.username %}" style="color: #BF442A; text-decoration: none">
        Автор: {{ post.author.get_full_name }}
        </a> 
      </li>
      <li style="color: #2ABFA2">
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      <a href="{% url 'posts:post_detail' post_id=post.id %}" style="color: #E5E7E9; text-decoration: none">{{ post.text }}</a>
    </p>
    {% thumbnail post.image "950x400" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if not foorloop.last %}<hr>{% endif %}
    {% endfor%}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% load cache %}
{% cache 20 index_page %}
{% block content %}

  <h1 style="margin-top: 100px; margin-bottom: 30px">Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' %}

  {% for post in page_obj %}
  <ul>
    <li>
      <a href="{% url 'posts:profile' username=post.author.username %}" style="color: #BF442A; text-decoration: none">
        Автор: {{ post.author.get_full_name }}
      </a>  
    </li>
    <li style="color: #2ABFA2">
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <a href="{% url 'posts:post_detail' post_id=post.id %}" style="color: #E5E7E9; text-decoration: none">{{ post.text }}</a>
    {% thumbnail post.image "950x400" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if post.group %}
      <p>    
        <a href="{% url 'posts:group_posts' slug=post.group.slug %}" style="color:#2AA6BF; text-decoration: none">{{  post.group.title  }} *</a>
      </p>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}
{% endcache %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
  <head>  
    {% block title %}
      Пост {{ post.text|truncatewords:30 }}
    {% endblock %}
    {% block content %}
      <div class="row" style="margin-top: 60px; margin-bottom: 30px">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">

            <li class="list-group-item" style="background-color: #232323 ; color: #E5E7E9 ; text-decoration: none">
              <a href="{% url 'posts:profile' username=post.author.username %}" style="color: #BF442A; text-decoration: none">
                {{ post.author.get_full_name }} - {{ author_posts_count }} постов
              </a>
            </li>

            {% if post.group %}   
              <li class="list-group-item" style="background-color: #232323 ; color: #2AA6BF ; text-decoration: none">
                <a href="{% url 'posts:group_posts' slug=post.group.slug %}" style="color:#2AA6BF; text-decoration: none">{{  post.group.title  }} *</a>               
              </li>
            {% endif %}

              <li class="list-group-item" style="background-color: #232323; color: #2ABFA2">
                Опубликовано: {{ post.pub_date|date:"d E Y" }}
              </li>

              {% if if_author %}           

              <li class="list-group-item" style="background-color: #232323">
                <button type='submit' class="btn btn-warning">
                  <a href="{% url 'posts:post_edit' post_id=post.id %}" style="color: #232323; text-decoration: none">Редактировать</a>
                </button>
              </li>

              <li class="list-group-item" style="background-color: #232323">
                <button type='submit' class="btn btn-warning">
                  <a href="{% url 'posts:post_delete' post_id=post.id %}" style="color: #232323; text-decoration: none">Удалить</a>
                </button>
              </li>

              {% endif %}
                
          </ul>
          </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text }}
          </p>
          <p>
          {% thumbnail post.image "950x400" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </p>

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body" >
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}" style="color: #E5E7E9; text-decoration: none">
                    <span style="color: #BF442A">{{ comment.author.username }}</span> - <span style="color: #2ABFA2"> {{ comment.created|date:"H:i d/n/Y e" }}</span>
                  </a>
                </h5>
                  <p>
                    {{ comment.text }}
                  </p>
              </div>
            </div>
         {% endfor %} 

          {% if user.is_authenticated %}
            <div class="card my-4 col-6 col-md-12" style="background-color: #BF442A">
              <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body col-6 col-md-12" >
                  <form method="post" action="{% url 'posts:add_comment' post.id %}" >
                  {% csrf_token %}      
                    <div class="form-group mb-2" >
                      {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-warning">Отправить</button>
                  </form>
                </div>
            </div>
          {% endif %}

        </article>
      </div>
    {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}
    Профайл пользователя {{ author.get_full_name }}
    {% endblock %}
    {% block content %}
      <div class="container py-5">    
        <div class="mb-5">    
          <h1 style="margin-top: 50px; margin-bottom: 30px">
            Все посты пользователя {{ author.get_full_name }}
          </h1>
          <h3>Всего постов: {{ posts_count }}</h3>
            {% if user.is_authenticated %}
              {% if following %}
                <a
                  class="btn btn-lg btn-warning"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                <a
                  class="btn btn-lg btn-warning"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                  Подписаться
                </a>
             {% endif %}
            {% else %}
                <p >
                  Авторизуйся, чтобы подписаться
                </p>
            {% endif %}

        </div>
        {% if post.group %} 
        {% endif %}
        <article>
          {% for post in page_obj %}
          <ul>
            <li style="color: #BF442A; text-decoration: none">
              Автор: {{ author.get_full_name }}
            </li>
            <li style="color: #2ABFA2">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
             <a href="{% url 'posts:post_detail' post_id=post.id %}" style="color: #E5E7E9; text-decoration: none">{{ post.text }}</a>
          </p>
          {% thumbnail post.image "950x400" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </article>
          {% if post.group %}
          <a href="{% url 'posts:group_posts' slug=post.group.slug %}" style="color:#2AA6BF; text-decoration: none">{{  post.group.title  }} *</a>  
          {% endif %}      
        <hr>
        {% if not forloop.last %}
          <hr>
          {% endif %}
            {% endfor %}
          {% include 'posts/includes/paginator.html' %}
      </div>
      {% endblock %}